# ~/.config/kitty/kitty.conf
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        10.0
symbol_map U+E0A0-U+E0D4,U+E700-U+E7C5,U+F000-U+F2FF,U+F400-U+F532 Symbols Nerd Font Mono
cursor            #c0caf5
cursor_text_color #1a1b26
selection_foreground #1a1b26
selection_background #7aa2f7
url_color #73daca
active_border_color   #7aa2f7
inactive_border_color #292e42
bell_border_color      #f7768e
tab_bar_style          powerline
tab_powerline_style    slanted
tab_bar_edge           bottom
tab_bar_background     #1a1b26
active_tab_foreground  #1a1b26
active_tab_background  #7aa2f7
active_tab_font_style  bold
inactive_tab_foreground #565f89
inactive_tab_background #24283b
foreground #c0caf5
background #1a1b26
background_opacity 1.0
color0  #15161e
color8  #414868
color1  #f7768e
color9  #f7768e
color2  #9ece6a
color10 #9ece6a
color3  #e0af68
color11 #e0af68
color4  #7aa2f7
color12 #7aa2f7
color5  #bb9af7
color13 #bb9af7
color6  #7dcfff
color14 #7dcfff
color7  #a9b1d6
color15 #c0caf5
enable_audio_bell no
window_alert_on_bell no
confirm_os_window_close 0
